services:
  database:
    image: mysql:8.4
    container_name: database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    volumes:
      - ./server:/app/server
      - /app/node_modules
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - 3001:3001
    depends_on:
      - database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    volumes:
      - ./client:/app/client
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - database

volumes:
  mysql_data: